=== sebvc/tc3-xplanar-simple-ptp/Packages/Beckhoff.TwinCAT.HMI.EcDiagnostics.24.0.7/runtimes/win-x64/native/TcHmiEcDiagnostics.Schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "EcDiagnosticsProcessDataSubItems": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "path": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "bitOffset": {
            "type": "integer"
          },
          "bitLength": {
            "type": "integer"
          },
          "subItems": {
            "$ref": "#/definitions/EcDiagnosticsProcessDataSubItems"
          }
        },
        "required": [
          "name",
          "path",
          "type",
          "bitOffset",
          "bitLength"
        ]
      }
    },
    "slave": {
      "configDescription": "descSlave",
      "type": "object",
      "properties": {
        "EtherCAT": {
          "type": "object",
          "properties": {
            "identity": {
              "type": "object",
              "properties": {
                "addrs": {
                  "type": "object",
                  "properties": {
                    "autoInc": {
                      "type": "integer"
                    },
                    "phys": {
                      "type": "integer"
                    }
                  },
                  "required": [
                    "autoInc",
                    "phys"
                  ]
                },
                "name": {
                  "type": "string"
                },
                "product": {
                  "type": "integer"
                },
                "revision": {
                  "type": "integer"
                },
                "serial": {
                  "type": "integer"
                },
                "productionInfo": {
                  "type": "object",
                  "properties": {
                    "firmwareVersion": {
                      "type": "integer"
                    },
                    "hardwareVersion": {
                      "type": "integer"
                    },
                    "date": {
                      "type": "object",
                      "properties": {
                        "year": {
                          "type": "integer"
                        },
                        "calendarWeek": {
                          "type": "integer"
                        },
                        "dayOfWeek": {
                          "type": "integer"
                        }
                      },
                      "required": [
                        "year",
                        "calendarWeek",
                        "dayOfWeek"
                      ]
                    }
                  },
                  "required": [
                    "firmwareVersion",
                    "hardwareVersion"
                  ]
                },
                "type": {
                  "type": "string"
                },
                "vendor": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "memberNameLong": {
                      "type": "string"
                    },
                    "memberNameShort": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "id",
                    "memberNameLong",
                    "memberNameShort"
                  ]
                }
              },
              "required": [
                "addrs",
                "name",
                "product",
                "revision",
                "serial",
                "type",
                "vendor"
              ]
            },
            "syncUnitsAssignment": {
              "type": "array",
              "items": [
                {
                  "type": "integer"
                }
              ]
            }
          },
          "required": [
            "identity",
            "syncUnitsAssignment"
          ]
        },
        "hotConnect": {
          "type": "object",
          "properties": {
            "isHotConnectHead": {
              "type": "boolean"
            },
            "isHotConnectSlave": {
              "type": "boolean"
            },
            "slaveCountActual": {
              "type": "integer"
            },
            "slaveCountConfig": {
              "type": "integer"
            }
          },
          "required": [
            "isHotConnectHead",
            "isHotConnectSlave",
            "slaveCountActual",
            "slaveCountConfig"
          ]
        },
        "ports": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "autoIncAddr": {
                  "type": "integer"
                },
                "configured": {
                  "type": "boolean"
                },
                "physAddr": {
                  "type": "integer"
                },
                "physic": {
                  "type": "integer"
                },
                "redundancy": {
                  "type": "boolean"
                },
                "redundancyPath": {
                  "type": "boolean"
                },
                "configuredSlave": {
                  "$ref": "#/definitions/slave"
                }
              },
              "required": [
                "autoIncAddr",
                "configured",
                "physAddr",
                "physic"
              ]
            }
          ]
        },
        "processData": {
          "type": "object",
          "properties": {
            "in": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "entries": {
                      "type": "array",
                      "items": [
                        {
                          "type": "object",
                          "properties": {
                            "bitLength": {
                              "type": "integer"
                            },
                            "index": {
                              "type": "string"
                            },
                            "name": {
                              "type": "string"
                            },
                            "subIndex": {
                              "type": "string"
                            },
                            "subItems": {
                              "$ref": "#/definitions/EcDiagnosticsProcessDataSubItems"
                            },
                            "type": {
                              "type": "string"
                            }
                          },
                          "required": [
                            "bitLength",
                            "index",
                            "name",
                            "subIndex",
                            "type"
                          ]
                        }
                      ]
                    },
                    "index": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "entries",
                    "index",
                    "name"
                  ]
                }
              ]
            },
            "out": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "entries": {
                      "type": "array",
                      "items": [
                        {
                          "type": "object",
                          "properties": {
                            "bitLength": {
                              "type": "integer"
                            },
                            "index": {
                              "type": "string"
                            },
                            "name": {
                              "type": "string"
                            },
                            "subIndex": {
                              "type": "string"
                            },
                            "subItems": {
                              "$ref": "#/definitions/EcDiagnosticsProcessDataSubItems"
                            },
                            "type": {
                              "type": "string"
                            }
                          },
                          "required": [
                            "bitLength",
                            "index",
                            "name",
                            "subIndex",
                            "type"
                          ]
                        }
                      ]
                    },
                    "index": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "entries",
                    "index",
                    "name"
                  ]
                }
              ]
            }
          },
          "required": [
            "in",
            "out"
          ]
        }
      },
      "required": [
        "EtherCAT",
        "hotConnect",
        "ports",
        "processData"
      ]
    },
    "EcDiagnosticsProcessDataObjectEntryID": {
      "configDescription": "descEcDiagnosticsProcessDataObjectEntryID",
      "type": "object",
      "properties": {
        "io": {
          "type": "string"
        },
        "objectIndex": {
          "type": "string"
        },
        "entryIndex": {
          "type": "string"
        },
        "entrySubIndex": {
          "type": "string"
        },
        "entryPropertyName": {
          "type": "string"
        }
      },
      "required": [
        "io",
        "objectIndex",
        "entryIndex",
        "entrySubIndex"
      ]
    },
    "EcDiagnosticsProcessDataObjectEntryValue": {
      "configDescription": "descEcDiagnosticsProcessDataObjectEntryValue",
      "type": "object",
      "properties": {
        "entryValue": {}
      },
      "required": [
        "entryValue"
      ]
    },
    "EcDiagnosticsProcessDataInOutValues": {
      "configDescription": "descEcDiagnosticsProcessDataInOutValues",
      "type": "object",
      "properties": {
        "entries": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "index": {
                  "type": "string"
                },
                "subIndex": {
                  "type": "string"
                },
                "value": {},
                "forced": {
                  "type": "boolean"
                },
                "forcedProperties": {
                  "type": "object",
                  "additionalProperties": {
                    "type": "boolean"
                  }
                },
                "error": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number"
                    },
                    "message": {
                      "type": "string"
                    },
                    "reason": {
                      "type": "string"
                    }
                  }
                }
              },
              "required": [
                "index",
                "subIndex"
              ]
            }
          ]
        },
        "index": {
          "type": "string"
        }
      },
      "required": [
        "in",
        "out"
      ]
    }
  },
  "properties": {
    "devices": {
      "type": "object",
      "configDescription": "devices",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "enabled": {
            "type": "boolean",
            "default": true
          },
          "targetNetId": {
            "type": "string",
            "format": "amsnetid",
            "optionMethod": {
              "symbol": "ADS.ListRoutes"
            }
          },
          "masterNetId": {
            "type": "string",
            "format": "amsnetid",
            "optionMethod": {
              "symbol": "{domain}.ListMastersOfRoute",
              "writeValue": {
                "$data": "#/properties/devices/additionalProperties/targetNetId"
              }
            }
          }
        },
        "required": [
          "enabled",
          "targetNetId",
          "masterNetId"
        ]
      },
      "defaultConfigurable": true,
      "default": {
        "Device1": {
          "enabled": true,
          "targetNetId": "0.0.0.0.1.1",
          "masterNetId": "0.0.0.0.2.1"
        }
      }
    },
    "runtimeStateCheckTimeout": {
      "configDescription": "descRuntimeStateCheckTimeout",
      "type": "string",
      "format": "timespan",
      "default": "PT5S",
      "formatMinimum": "PT1S",
      "formatMaximum": "PT30S",
      "visibility": "HideInEngineering"
    },
    "timeout": {
      "configDescription": "descTimeout",
      "type": "string",
      "format": "timespan",
      "default": "PT5S",
      "formatMinimum": "PT1S",
      "formatMaximum": "PT30S",
      "visibility": "HideInEngineering"
    },
    "updateIntervals": {
      "type": "object",
      "description": "Minimum time between two asynchronous requests for each request.",
      "properties": {
        "MasterList": {
          "type": "integer",
          "default": 1000,
          "description": "Minimum time between two requests in ms."
        },
        "MasterOnlineInfo": {
          "type": "integer",
          "default": 300,
          "description": "Including frame statistic (sent frames, damaged frames, lost frames, ...) and master state."
        },
        "Slaves": {
          "type": "integer",
          "default": 1000
        },
        "SlavesOnlineInfo": {
          "type": "integer",
          "default": 1000
        },
        "ProcessDataValues": {
          "type": "integer",
          "default": 1000
        }
      },
      "required": [
        "MasterList",
        "MasterOnlineInfo",
        "Slaves",
        "SlavesOnlineInfo",
        "ProcessDataValues"
      ]
    },
    "vendorsOverwrite": {
      "type": "object",
      "configDescription": "descVendorsOverwrite",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "longName": {
            "type": "string"
          },
          "shortName": {
            "type": "string"
          },
          "devices": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "pattern": {
                  "type": "string"
                },
                "longName": {
                  "type": "string"
                },
                "shortName": {
                  "type": "string"
                }
              },
              "required": [
                "pattern"
              ],
              "additionalProperties": false
            }
          }
        },
        "required": [
          "devices"
        ],
        "additionalProperties": false
      },
      "default": {
        "1": {
          "longName": "EtherCAT Technology Group",
          "shortName": "ETG"
        },
        "2": {
          "longName": "Beckhoff Automation GmbH & Co. KG",
          "shortName": "Beckhoff"
        }
      }
    }
  },
  "type": "object",
  "required": [
    "devices",
    "vendorsOverwrite",
    "updateIntervals"
  ],
  "additionalProperties": false
}

=== sebvc/tc3-xplanar-simple-ptp/Xplanar-HMI/Server/TcHmiEcDiagnostics/TcHmiEcDiagnostics.Config.default.json
{
    "devices": {
        "IO (EtherCAT)": {
            "enabled": true,
            "masterNetId": "0.0.0.0.2.1",
            "targetNetId": "169.254.221.1.1.1"
        },
        "XPlanar": {
            "enabled": true,
            "masterNetId": "0.0.0.0.4.1",
            "targetNetId": "169.254.221.1.1.1"
        }
    },
    "runtimeStateCheckTimeout": "PT5S",
    "updateIntervals": {
        "MasterList": 1000,
        "MasterOnlineInfo": 300,
        "ProcessDataValues": 1000,
        "Slaves": 1000,
        "SlavesOnlineInfo": 1000
    },
    "vendorsOverwrite": {
        "1": {
            "devices": [],
            "longName": "EtherCAT Technology Group",
            "shortName": "ETG"
        },
        "2": {
            "devices": [],
            "longName": "Beckhoff Automation GmbH & Co. KG",
            "shortName": "Beckhoff"
        }
    }
}
